import Head from "next/head";
import Logo from "../components/Icons/Logo";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <div className="container">
        <Head>
          <title>8bitStore</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Logo height={100} width={100} />
          <motion.h1
            className="title"
            style={{ fontSize: "1.2rem", marginTop: "25px" }}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1, type: "spring", duration: 1.4 }}
          >
            8bitfootball
          </motion.h1>
          <motion.p
            className="title"
            style={{
              fontSize: "1rem",
              letterSpacing: "2px",
              color: "#444",
              fontFamily: "Bebas Neue, cursive",
            }}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.3, type: "spring", duration: 1.4 }}
          >
            store
          </motion.p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://mariodev.netlify.app"
            target="_blank"
            rel="noopener noreferrer"
          >
            By mariodev
          </a>
        </footer>
      </div>

      <style jsx>{`
        p {
          font-family: "Bebas Neue", cursive;
          color: #666;
        }
      `}</style>
    </>
  );
}
