import Head from "next/head";
import WelcomeLogo from "../components/Icons/WelcomeLogo";
import { motion } from "framer-motion";
import { Box, Flex, Text } from "@chakra-ui/react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  setTimeout(() => {
    router.replace("/Home");
  }, 3500);

  return (
    <>
      <Head>
        <title>8bitStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        style={{
          display: "flex",
          height: "100vh",
          justifyContent: "center",
          alignItems: "center",
        }}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ scale: 0 }}
        transition={{
          duration: 0.75,
          ease: "easeInOut",
        }}
      >
        <Flex direction={"column"} align={"center"} fontWeight={600}>
          <WelcomeLogo />
          <motion.h1
            style={{
              fontSize: "1.5rem",
              marginTop: "20px",
            }}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1, type: "spring", duration: 1.4 }}
          >
            8bitfootball
          </motion.h1>
          <motion.h2
            style={{
              marginTop: "-5px",
              letterSpacing: "2px",
              color: "#444",
            }}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.3, type: "spring", duration: 1.4 }}
          >
            STORE
          </motion.h2>
        </Flex>
      </motion.div>
    </>
  );
}
