import React from "react";
import {
  ArgentinaHomeShirt,
  ArgentinaAwayShirt,
  CroaciaHomeShirt,
  BrasilHomeShirt02,
  FranceHomeShirt98,
  ArgentinaHomeShirt02,
  MexicoHomeShirt98,
  JuventusAwayShirt96,
  EnglandHomeShirt98,
  AlemaniaHomeShirt90,
  CroaciaHomeShirt98,
} from "./ShirtsSvg";

export const ShirtsList = [
  {
    id: 1,
    title: "Argentina 2022 Home Shirt",
    price: "80",
    type: "Home",
    colors: "White / Light Blue",
    img: <ArgentinaHomeShirt />,
    newArrival: true,
    retro: false,
  },
  {
    id: 2,
    title: "Argentina 2022 Away Shirt",
    price: "70",
    type: "Away",
    colors: "Violet",
    img: <ArgentinaAwayShirt />,
    newArrival: true,
    retro: false,
  },
  {
    id: 3,
    title: "Croacia 2022",
    price: "50",
    type: "Home",
    colors: "White / Red",
    img: <CroaciaHomeShirt />,
    newArrival: true,
    retro: false,
  },
  {
    id: 4,
    title: "Brasil Home 2002",
    price: "70",
    type: "Home",
    colors: "White / Yellow",
    img: <BrasilHomeShirt02 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 5,
    title: "France Home 1998",
    price: "70",
    type: "Home",
    colors: "Blue / Red / White",
    img: <FranceHomeShirt98 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 6,
    title: "Argentina 2002 Away",
    price: "100",
    type: "Away",
    img: <ArgentinaHomeShirt02 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 7,
    title: "Mexico 1998 Home",
    price: "120",
    type: "Home",
    img: <MexicoHomeShirt98 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 8,
    title: "Juventus 1996 Away",
    price: "120",
    type: "Away",
    img: <JuventusAwayShirt96 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 9,
    title: "England 1998 Home",
    price: "120",
    type: "Home",
    img: <EnglandHomeShirt98 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 10,
    title: "Alemania 1990 Home",
    price: "120",
    type: "Home",
    img: <AlemaniaHomeShirt90 />,
    newArrival: false,
    retro: true,
  },
  {
    id: 11,
    title: "Croacia 1998 Home",
    price: "120",
    type: "Home",
    img: <CroaciaHomeShirt98 />,
    newArrival: false,
    retro: true,
  },
];
